# Use an official Python runtime as a parent image
FROM python:3.12-slim

# Set the working directory in the container
WORKDIR /app

# Copy the current directory contents into the container
COPY . .

# Install the required system packages
RUN apt-get update && apt-get install -y \
    build-essential \
    libpq-dev \
    curl \
    && rm -rf /var/lib/apt/lists/*

# Install any needed Python packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Copy .env file into the container
COPY .env .env

# Expose port 8501 for Streamlit
EXPOSE 8501

# Run the RAG app when the container launches
CMD ["streamlit", "run", "Inawiga/app.py"]
